---
apiVersion: v1
kind: Service
metadata:
  name: svc-fe-review-vntrip-vn
  namespace: vntrip-prod
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fe-review-vntrip-vn
  sessionAffinity: None
  type: ClusterIP
