export const dataReviewDefault = [
    {
        key: '1',
        proportion: '100%',
        stt: 'I',
        phone: "20%",
        title: "NĂNG LỰC & KẾT QUẢ CÔNG VIỆC",
        description : "Làm review App",
        pointUser : 3,
        pointManager : 0,
    },
    {
        key: '2',
        proportion: '50%',
        stt: '1',
        phone: "80%",
        title: "Khối lượng công việc trong tháng",
        pointUser : 3,
        pointManager : undefined,
    },
    {
        key: '3',
        proportion: '50%',
        stt: '2',
        title: "Chất lượng công việc đã hoàn thành",
    },
    {
        key: '4',
        proportion: '100%',
        stt: 'II',
        phone: "100%",
        title: "BONUS",
    },
    {
        key: '5',
        proportion: '30%',
        stt: '1',
        phone: "100%",
        title: "Hỗ trợ ngoài công việc chính",
    },
    {
        key: '6',
        proportion: '30%',
        stt: '2',
        phone: "100%",
        title: "Làm thêm ngoài giờ",
    },
    {
        key: '7',
        proportion: '20%',
        stt: '3',
        phone: "100%",
        title: "Chia sẻ kiến thức công việc & chuyên môn",
    },
    {
        key: '8',
        proportion: '20%',
        stt: '4',
        phone: "100%",
        title: "Khả năng sáng tạo, áp dụng công nghệ/quy trình trong công việc",
    },
    {
        key: '9',
        proportion: '100%',
        stt: 'III',
        phone: "100%",
        title: "THÁI ĐỘ LÀM VIỆC & TEAMWORK",
    },
    {
        key: '10',
        proportion: '15%',
        stt: '1',
        phone: "100%",
        title: "Tính chủ động trong công việc",
    },
    {
        key: '11',
        proportion: '15%',
        stt: '2',
        phone: "100%",
        title: "Tinh thần làm việc nhóm, thái độ hợp tác trong nội bộ/bên ngoài",
    },
    {
        key: '12',
        proportion: '15%',
        stt: '3',
        phone: "100%",
        title: "Thái độ làm việc",
    },
    {
        key: '13',
        proportion: '15%',
        stt: '4',
        phone: "100%",
        title: "Tuân thủ nội quy",
    },
    {
        key: '14',
        proportion: '20%',
        stt: '5',
        phone: "100%",
        title: "Văn hóa ứng xử trong công ty",
    },
    {
        key: '15',
        proportion: '15%',
        stt: '6',
        phone: "100%",
        title: "Thái độ và tác phong làm việc",
    },
    {
        key: '16',
        proportion: '5%',
        stt: '7',
        phone: "100%",
        title: "Tham gia hoạt động phong trào",
    },
];

export const point = [
    {
        value: 0,
        label: 0,
    },
    {
        value: 1,
        label: 1,
    },
    {
        value: 2,
        label: 2,
    },
    {
        value: 3,
        label: 3,
    },
    {
        value: 4,
        label: 4,
    },
];